/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Campaigns */
        get: operations["list_campaigns_api_campaigns_get"];
        put?: never;
        /** Create Campaign */
        post: operations["create_campaign_api_campaigns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Campaign */
        get: operations["get_campaign_api_campaigns__campaign_id__get"];
        put?: never;
        post?: never;
        /** Delete Campaign */
        delete: operations["delete_campaign_api_campaigns__campaign_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/recipients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recipients */
        get: operations["list_recipients_api_campaigns__campaign_id__recipients_get"];
        put?: never;
        /** Add Recipients */
        post: operations["add_recipients_api_campaigns__campaign_id__recipients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/import-csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Csv */
        post: operations["import_csv_api_campaigns__campaign_id__import_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Campaign */
        post: operations["start_campaign_api_campaigns__campaign_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Campaign */
        post: operations["stop_campaign_api_campaigns__campaign_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipients/{recipient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Recipient */
        delete: operations["delete_recipient_api_recipients__recipient_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/recipients/{recipient_id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Attachment */
        post: operations["upload_attachment_api_campaigns__campaign_id__recipients__recipient_id__attachments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttachmentRead
         * @description Ответ: метаданные вложения.
         */
        AttachmentRead: {
            /** Id */
            id: number;
            /** Filename */
            filename: string;
            /** Size */
            size: number;
        };
        /**
         * AttachmentReadEnvelope
         * @description Обёртка вложения.
         */
        AttachmentReadEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            result?: components["schemas"]["AttachmentRead"] | null;
            /** Error */
            error?: string | null;
        };
        /** Body_import_csv_api_campaigns__campaign_id__import_csv_post */
        Body_import_csv_api_campaigns__campaign_id__import_csv_post: {
            /** File */
            file: string;
        };
        /** Body_upload_attachment_api_campaigns__campaign_id__recipients__recipient_id__attachments_post */
        Body_upload_attachment_api_campaigns__campaign_id__recipients__recipient_id__attachments_post: {
            /** File */
            file: string;
        };
        /**
         * CampaignRead
         * @description Ответ: данные кампании + необязательные счётчики прогресса.
         */
        CampaignRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Subject */
            subject: string;
            /** Body */
            body: string;
            status: components["schemas"]["CampaignStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Totals */
            totals?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * CampaignReadEnvelope
         * @description Обёртка одной кампании.
         */
        CampaignReadEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            result?: components["schemas"]["CampaignRead"] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * CampaignStatus
         * @enum {string}
         */
        CampaignStatus: "new" | "in_progress" | "done" | "error";
        /**
         * CreateCampaign
         * @description Тело запроса на создание кампании.
         */
        CreateCampaign: {
            /** Name */
            name: string;
            /** Subject */
            subject: string;
            /** Body */
            body: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImportCsvResult
         * @description Результат импорта получателей из CSV.
         */
        ImportCsvResult: {
            /** Created */
            created: number;
            /**
             * Skipped
             * @default []
             */
            skipped: [
                number,
                string,
                string
            ][];
            /**
             * Problems
             * @default []
             */
            problems: string[];
        };
        /**
         * ImportCsvResultEnvelope
         * @description Обёртка результата импорта CSV.
         */
        ImportCsvResultEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            result?: components["schemas"]["ImportCsvResult"] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * ListCampaignReadEnvelope
         * @description Обёртка списка кампаний.
         */
        ListCampaignReadEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            /** Result */
            result?: components["schemas"]["CampaignRead"][] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * ListRecipientReadEnvelope
         * @description Обёртка списка получателей.
         */
        ListRecipientReadEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            /** Result */
            result?: components["schemas"]["RecipientRead"][] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * MessageOut
         * @description Универсальный ответ операции (старт/стоп/импорт).
         */
        MessageOut: {
            /** Detail */
            detail: string;
            /** Campaign Id */
            campaign_id: number;
        };
        /**
         * MessageOutEnvelope
         * @description Обёртка служебного сообщения (старт/стоп).
         */
        MessageOutEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            result?: components["schemas"]["MessageOut"] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * RecipientCreate
         * @description Тело запроса на добавление одного получателя.
         */
        RecipientCreate: {
            /** Email */
            email: string;
            /** Name */
            name?: string | null;
        };
        /**
         * RecipientRead
         * @description Ответ: получатель со статусом и списком вложений.
         */
        RecipientRead: {
            /** Id */
            id: number;
            /** Campaign Id */
            campaign_id: number;
            /** Email */
            email: string;
            /** Name */
            name?: string | null;
            status: components["schemas"]["RecipientStatus"];
            /** Error */
            error?: string | null;
            /** Sent At */
            sent_at?: string | null;
            /**
             * Attachments
             * @default []
             */
            attachments: components["schemas"]["AttachmentRead"][];
        };
        /**
         * RecipientStatus
         * @enum {string}
         */
        RecipientStatus: "pending" | "sent" | "failed" | "skipped";
        /**
         * RecipientsBulk
         * @description Массовое добавление получателей.
         */
        RecipientsBulk: {
            /** Items */
            items: components["schemas"]["RecipientCreate"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_campaigns_api_campaigns_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListCampaignReadEnvelope"];
                };
            };
        };
    };
    create_campaign_api_campaigns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCampaign"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignReadEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_campaign_api_campaigns__campaign_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignReadEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_campaign_api_campaigns__campaign_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOutEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recipients_api_campaigns__campaign_id__recipients_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRecipientReadEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_recipients_api_campaigns__campaign_id__recipients_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipientsBulk"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRecipientReadEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_csv_api_campaigns__campaign_id__import_csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_csv_api_campaigns__campaign_id__import_csv_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportCsvResultEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_campaign_api_campaigns__campaign_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOutEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_campaign_api_campaigns__campaign_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOutEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_recipient_api_recipients__recipient_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipient_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_attachment_api_campaigns__campaign_id__recipients__recipient_id__attachments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
                recipient_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_attachment_api_campaigns__campaign_id__recipients__recipient_id__attachments_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentReadEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
