/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Campaigns */
        get: operations["list_campaigns_api_campaigns_get"];
        put?: never;
        /** Create Campaign */
        post: operations["create_campaign_api_campaigns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Campaign */
        get: operations["get_campaign_api_campaigns__campaign_id__get"];
        put?: never;
        post?: never;
        /** Delete Campaign */
        delete: operations["delete_campaign_api_campaigns__campaign_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/recipients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recipients */
        get: operations["list_recipients_api_campaigns__campaign_id__recipients_get"];
        put?: never;
        /** Add Recipients */
        post: operations["add_recipients_api_campaigns__campaign_id__recipients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/recipients/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Recipients Import */
        post: operations["preview_recipients_import_api_campaigns__campaign_id__recipients_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/recipients/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Recipients */
        post: operations["import_recipients_api_campaigns__campaign_id__recipients_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/configs/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Configs
         * @description Ставит в очередь конфиги без файла — генерацию делает фоновый воркер.
         */
        post: operations["generate_configs_api_campaigns__campaign_id__configs_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Campaign */
        post: operations["start_campaign_api_campaigns__campaign_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Campaign */
        post: operations["stop_campaign_api_campaigns__campaign_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipients/{recipient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Recipient */
        delete: operations["delete_recipient_api_recipients__recipient_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/configs/{config_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Config
         * @description Отдаёт файл конфига. Ответ бинарный, без обёртки ApiEnvelope.
         */
        get: operations["download_config_api_configs__config_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CampaignRead
         * @description Ответ: данные кампании + необязательные счётчики прогресса.
         */
        CampaignRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Subject */
            subject: string;
            /** Body */
            body: string;
            status: components["schemas"]["CampaignStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Totals */
            totals?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * CampaignReadEnvelope
         * @description Обёртка одной кампании.
         */
        CampaignReadEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            result?: components["schemas"]["CampaignRead"] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * CampaignStatus
         * @enum {string}
         */
        CampaignStatus: "new" | "in_progress" | "done" | "done_with_errors" | "error";
        /**
         * ConfigRead
         * @description Ответ: конфиг получателя со статусом генерации (без содержимого файла).
         */
        ConfigRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            status: components["schemas"]["ConfigStatus"];
            /** Filename */
            filename?: string | null;
            /**
             * Size
             * @default 0
             */
            size: number;
            /** Error */
            error?: string | null;
        };
        /**
         * ConfigStatus
         * @enum {string}
         */
        ConfigStatus: "pending" | "queued" | "generating" | "ready" | "failed";
        /**
         * CreateCampaign
         * @description Тело запроса на создание кампании.
         */
        CreateCampaign: {
            /** Name */
            name: string;
            /** Subject */
            subject: string;
            /** Body */
            body: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImportGroup
         * @description Одно письмо: получатель и конфиги, которые ему уедут.
         */
        ImportGroup: {
            /** Email */
            email: string;
            /** Configs */
            configs: string[];
            /**
             * Existing Configs
             * @default []
             */
            existing_configs: string[];
            /**
             * Is Existing
             * @default false
             */
            is_existing: boolean;
        };
        /**
         * ImportPreview
         * @description Предпросмотр импорта: что получится, если сохранить.
         */
        ImportPreview: {
            /** Groups */
            groups: components["schemas"]["ImportGroup"][];
            /**
             * Problems
             * @default []
             */
            problems: components["schemas"]["ImportRowProblem"][];
            /** Total Rows */
            total_rows: number;
            /** Total Configs */
            total_configs: number;
        };
        /**
         * ImportPreviewEnvelope
         * @description Обёртка предпросмотра импорта получателей.
         */
        ImportPreviewEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            result?: components["schemas"]["ImportPreview"] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * ImportResult
         * @description Итог импорта.
         */
        ImportResult: {
            /** Created Recipients */
            created_recipients: number;
            /** Updated Recipients */
            updated_recipients: number;
            /** Created Configs */
            created_configs: number;
            /**
             * Problems
             * @default []
             */
            problems: components["schemas"]["ImportRowProblem"][];
        };
        /**
         * ImportResultEnvelope
         * @description Обёртка результата импорта получателей.
         */
        ImportResultEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            result?: components["schemas"]["ImportResult"] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * ImportRowProblem
         * @description Строка, которую не удалось разобрать.
         */
        ImportRowProblem: {
            /** Line */
            line: number;
            /** Raw */
            raw: string;
            /** Reason */
            reason: string;
        };
        /**
         * ListCampaignReadEnvelope
         * @description Обёртка списка кампаний.
         */
        ListCampaignReadEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            /** Result */
            result?: components["schemas"]["CampaignRead"][] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * ListRecipientReadEnvelope
         * @description Обёртка списка получателей.
         */
        ListRecipientReadEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            /** Result */
            result?: components["schemas"]["RecipientRead"][] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * MessageOut
         * @description Универсальный ответ операции (старт/стоп/импорт).
         */
        MessageOut: {
            /** Detail */
            detail: string;
            /** Campaign Id */
            campaign_id: number;
        };
        /**
         * MessageOutEnvelope
         * @description Обёртка служебного сообщения (старт/стоп).
         */
        MessageOutEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            result?: components["schemas"]["MessageOut"] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * RecipientCreate
         * @description Тело запроса на добавление одного получателя.
         */
        RecipientCreate: {
            /** Email */
            email: string;
            /** Name */
            name?: string | null;
            /**
             * Configs
             * @default []
             */
            configs: string[];
        };
        /**
         * RecipientRead
         * @description Ответ: получатель со статусом отправки и списком конфигов.
         */
        RecipientRead: {
            /** Id */
            id: number;
            /** Campaign Id */
            campaign_id: number;
            /** Email */
            email: string;
            /** Name */
            name?: string | null;
            status: components["schemas"]["RecipientStatus"];
            /** Error */
            error?: string | null;
            /** Sent At */
            sent_at?: string | null;
            /**
             * Configs
             * @default []
             */
            configs: components["schemas"]["ConfigRead"][];
        };
        /**
         * RecipientStatus
         * @enum {string}
         */
        RecipientStatus: "pending" | "sent" | "failed";
        /**
         * RecipientsBulk
         * @description Массовое добавление получателей.
         */
        RecipientsBulk: {
            /** Items */
            items: components["schemas"]["RecipientCreate"][];
        };
        /**
         * RecipientsImportText
         * @description Тело запроса: вставленный из таблицы текст (две колонки через таб).
         */
        RecipientsImportText: {
            /** Text */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_campaigns_api_campaigns_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListCampaignReadEnvelope"];
                };
            };
        };
    };
    create_campaign_api_campaigns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCampaign"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignReadEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_campaign_api_campaigns__campaign_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignReadEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_campaign_api_campaigns__campaign_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOutEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recipients_api_campaigns__campaign_id__recipients_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRecipientReadEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_recipients_api_campaigns__campaign_id__recipients_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipientsBulk"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRecipientReadEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_recipients_import_api_campaigns__campaign_id__recipients_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipientsImportText"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportPreviewEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_recipients_api_campaigns__campaign_id__recipients_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipientsImportText"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResultEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_configs_api_campaigns__campaign_id__configs_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOutEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_campaign_api_campaigns__campaign_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOutEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_campaign_api_campaigns__campaign_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOutEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_recipient_api_recipients__recipient_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipient_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_config_api_configs__config_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
